apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: sippy
    app.kubernetes.io/component: sippy
    app.kubernetes.io/instance: sippy
  name: sippy
  namespace: sippy
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sippy:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/openshift/sippy
      ref: master
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
# Can enable github webhook integration to build on merges:
# Otherwise use: oc start-build sippy
#  - github:
#     secretReference:
#       name: github-webhook-secret
#   type: GitHub

