apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: sippy-daemon
    app.kubernetes.io/component: sippy-daemon
    app.kubernetes.io/instance: sippy-daemon
  name: sippy-daemon
  namespace: sippy
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    deploymentconfig: sippy-daemon
  template:
    metadata:
      labels:
        deploymentconfig: sippy-daemon
    spec:
      volumes:
        - name: gcs-credentials
          secret:
            secretName: gcs-credentials
      containers:
      - name: sippy
        # image gets replaced due to use of the image stream tag below
        image: image-registry.openshift-image-registry.svc:5000/sippy/sippy:latest
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 2112
          protocol: TCP
        resources:
          requests:
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /bin/sippy
        args:
        - --mode=ocp
        - --init-database
        - --config=/config/openshift.yaml
        - --daemon-server
        - --comment-processing
        - --include-repo-commenting=origin
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcs/credentials
          - name: SIPPY_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                 name: sippy-github-token
                 key: token
        volumeMounts:
          - mountPath: /etc/gcs
            name: gcs-credentials
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sippy
      from:
        kind: ImageStreamTag
        name: sippy:latest
        namespace: sippy
    type: ImageChange
