apiVersion: v1
kind: Service
metadata:
  labels:
    app: sippy
    app.kubernetes.io/component: sippy
    app.kubernetes.io/instance: sippy
  name: sippy
  namespace: sippy
spec:
  ports:
  - name: www
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 2112
    protocol: TCP
  selector:
    deploymentconfig: sippy
  sessionAffinity: None
  type: ClusterIP
