apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: sippy
    app.kubernetes.io/component: sippy
    app.kubernetes.io/instance: sippy
  name: sippy
  namespace: sippy
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    deploymentconfig: sippy
  strategy:
    # This strategy ensures that on updates we roll out one container at a time, with a 10s
    # pause after each is ready.
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 10
      # TODO: investigate pre here to run a hook prior to each deployment and update db schema
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        deploymentconfig: sippy
    spec:
      containers:
      - image: quay.io/dgoodwin/sippy:latest
        imagePullPolicy: Always
        name: sippy
        ports:
        - name: www
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 2112
          protocol: TCP
        resources:
          limits:
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /bin/sippy
        args:
        - --local-data
        - /data
        - --mode=ocp
        - --db-only-mode
        - --server
        env:
          - name: SIPPY_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sippy
  triggers:
  - type: ConfigChange
