apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: sippy
    app.kubernetes.io/component: sippy
    app.kubernetes.io/instance: sippy
  name: sippy
  namespace: sippy
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    deploymentconfig: sippy
  strategy:
    # This strategy ensures that on updates we roll out one container at a time, with a 10s
    # pause after each is ready.
    type: Rolling
    rollingParams:
      # this pre hook runs once before each new deployment rollout begins.
      # we use this mechanism to update the db schema so pods don't start at once and
      # fight over making schema updates.
      pre:
        failurePolicy: Retry
        execNewPod:
          containerName: sippy
          command:
          - /bin/sippy
          - --init-database
          - --log-level=debug
          env:
          - name: SIPPY_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        deploymentconfig: sippy
    spec:
      containers:
      - name: sippy
        # image gets replaced due to use of the image stream tag below
        image: image-registry.openshift-image-registry.svc:5000/sippy/sippy:latest
        imagePullPolicy: Always
        ports:
        - name: www
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 2112
          protocol: TCP
        resources:
          requests:
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /bin/sippy
        args:
        - --mode=ocp
        - --db-only-mode
        - --server
        env:
          - name: SIPPY_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sippy
      from:
        kind: ImageStreamTag
        name: sippy:latest
        namespace: sippy
    type: ImageChange
