apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: sippy
    app.kubernetes.io/component: sippy
    app.kubernetes.io/instance: sippy
  name: sippy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: sippy
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: sippy
    spec:
      containers:      
      - image: image-registry.openshift-image-registry.svc:5000/bparees/sippy@sha256:a0d2bc5921154f87b991f206f6fdfdbca0d9e55c88c2c7a76dffe6997c9bbd14
        imagePullPolicy: Always
        name: sippy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /tmp/src/sippy
        args:
        - --local-data
        - /data
        - --release
        - "4.5"
        - --release
        - "4.4"
        - --release
        - "4.3"
        - --release
        - "4.2"
        - --server
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sippy
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sippy
      from:
        kind: ImageStreamTag
        name: sippy:latest
        namespace: bparees
    type: ImageChange
